# Generated by Django 3.2 on 2021-04-07 17:39

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=100, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('icone', stdimage.models.StdImageField(choices=[('lni-cog', 'engrenagem'), ('lni-leaf', 'folha'), ('lni-layers', 'design'), ('lni-laptop-phone', 'laptop'), ('lni-rocket', 'foguete')], max_length=17, upload_to='', verbose_name='icone')),
                ('texto', models.CharField(max_length=200, verbose_name='texto')),
                ('posicao', models.CharField(choices=[('box-item wow fadeInLeft', 'esquerda'), ('box-item wow fadeInRight', 'direita')], default=True, max_length=24, verbose_name='posicionamento')),
                ('delay_p', models.CharField(choices=[('0.3s', '0.3'), ('0.6s', '0.6'), ('0.9s', '0.9')], default=True, max_length=4, verbose_name='delay-posição')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('servico', models.CharField(max_length=100, verbose_name='Serviços')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'engrenagem'), ('lni-stats-up', 'gráficos'), ('lni-user', 'usuários'), ('lni-layers', 'design'), ('lni-mobile', 'mobile'), ('lni-rocket', 'foguete')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('bio', models.TextField(max_length=400, verbose_name='Bio')),
                ('imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem')),
                ('facebook', models.CharField(default='--', max_length=100, verbose_name='Facebook')),
                ('instragram', models.CharField(default='--', max_length=100, verbose_name='Instagram')),
                ('twitter', models.CharField(default='--', max_length=100, verbose_name='Twitter')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
